// Silinx - open-source components shipped with Silinx ISE (shown in Help ▸ About).
// Generated by scripts/third-party.mjs from the production dependencies: do not edit.
export const THIRD_PARTY = [
  {
    "name": "@yowasp/yosys",
    "version": "0.68.1207",
    "license": "ISC",
    "url": "https://yowasp.org/",
    "standalone": false
  },
  {
    "name": "accepts",
    "version": "1.3.8",
    "license": "MIT",
    "url": "jshttp/accepts",
    "standalone": false
  },
  {
    "name": "array-flatten",
    "version": "1.1.1",
    "license": "MIT",
    "url": "https://github.com/blakeembrey/array-flatten",
    "standalone": false
  },
  {
    "name": "body-parser",
    "version": "1.20.8",
    "license": "MIT",
    "url": "expressjs/body-parser",
    "standalone": false
  },
  {
    "name": "bytes",
    "version": "3.1.2",
    "license": "MIT",
    "url": "visionmedia/bytes.js",
    "standalone": false
  },
  {
    "name": "call-bind-apply-helpers",
    "version": "1.0.2",
    "license": "MIT",
    "url": "https://github.com/ljharb/call-bind-apply-helpers#readme",
    "standalone": false
  },
  {
    "name": "call-bound",
    "version": "1.0.4",
    "license": "MIT",
    "url": "https://github.com/ljharb/call-bound#readme",
    "standalone": false
  },
  {
    "name": "codemirror",
    "version": "5.65.21",
    "license": "MIT",
    "url": "https://codemirror.net/5/",
    "standalone": true
  },
  {
    "name": "content-disposition",
    "version": "0.5.4",
    "license": "MIT",
    "url": "jshttp/content-disposition",
    "standalone": false
  },
  {
    "name": "content-type",
    "version": "1.0.5",
    "license": "MIT",
    "url": "jshttp/content-type",
    "standalone": false
  },
  {
    "name": "cookie",
    "version": "0.7.2",
    "license": "MIT",
    "url": "jshttp/cookie",
    "standalone": false
  },
  {
    "name": "cookie-signature",
    "version": "1.0.7",
    "license": "MIT",
    "url": "https://github.com/visionmedia/node-cookie-signature",
    "standalone": false
  },
  {
    "name": "debug",
    "version": "2.6.9",
    "license": "MIT",
    "url": "https://github.com/visionmedia/debug",
    "standalone": false
  },
  {
    "name": "depd",
    "version": "2.0.0",
    "license": "MIT",
    "url": "dougwilson/nodejs-depd",
    "standalone": false
  },
  {
    "name": "destroy",
    "version": "1.2.0",
    "license": "MIT",
    "url": "stream-utils/destroy",
    "standalone": false
  },
  {
    "name": "dunder-proto",
    "version": "1.0.1",
    "license": "MIT",
    "url": "https://github.com/es-shims/dunder-proto#readme",
    "standalone": false
  },
  {
    "name": "ee-first",
    "version": "1.1.1",
    "license": "MIT",
    "url": "jonathanong/ee-first",
    "standalone": false
  },
  {
    "name": "elkjs",
    "version": "0.9.3",
    "license": "EPL-2.0",
    "url": "https://github.com/kieler/elkjs",
    "standalone": true
  },
  {
    "name": "encodeurl",
    "version": "2.0.0",
    "license": "MIT",
    "url": "pillarjs/encodeurl",
    "standalone": false
  },
  {
    "name": "es-define-property",
    "version": "1.0.1",
    "license": "MIT",
    "url": "https://github.com/ljharb/es-define-property#readme",
    "standalone": false
  },
  {
    "name": "es-errors",
    "version": "1.3.0",
    "license": "MIT",
    "url": "https://github.com/ljharb/es-errors#readme",
    "standalone": false
  },
  {
    "name": "es-object-atoms",
    "version": "1.1.2",
    "license": "MIT",
    "url": "https://github.com/ljharb/es-object-atoms#readme",
    "standalone": false
  },
  {
    "name": "escape-html",
    "version": "1.0.3",
    "license": "MIT",
    "url": "component/escape-html",
    "standalone": false
  },
  {
    "name": "etag",
    "version": "1.8.1",
    "license": "MIT",
    "url": "jshttp/etag",
    "standalone": false
  },
  {
    "name": "express",
    "version": "4.22.3",
    "license": "MIT",
    "url": "http://expressjs.com/",
    "standalone": false
  },
  {
    "name": "finalhandler",
    "version": "1.3.2",
    "license": "MIT",
    "url": "pillarjs/finalhandler",
    "standalone": false
  },
  {
    "name": "forwarded",
    "version": "0.2.0",
    "license": "MIT",
    "url": "jshttp/forwarded",
    "standalone": false
  },
  {
    "name": "fresh",
    "version": "0.5.2",
    "license": "MIT",
    "url": "jshttp/fresh",
    "standalone": false
  },
  {
    "name": "function-bind",
    "version": "1.1.2",
    "license": "MIT",
    "url": "https://github.com/Raynos/function-bind",
    "standalone": false
  },
  {
    "name": "get-intrinsic",
    "version": "1.3.0",
    "license": "MIT",
    "url": "https://github.com/ljharb/get-intrinsic#readme",
    "standalone": false
  },
  {
    "name": "get-proto",
    "version": "1.0.1",
    "license": "MIT",
    "url": "https://github.com/ljharb/get-proto#readme",
    "standalone": false
  },
  {
    "name": "gopd",
    "version": "1.2.0",
    "license": "MIT",
    "url": "https://github.com/ljharb/gopd#readme",
    "standalone": false
  },
  {
    "name": "has-symbols",
    "version": "1.1.0",
    "license": "MIT",
    "url": "https://github.com/ljharb/has-symbols#readme",
    "standalone": false
  },
  {
    "name": "hasown",
    "version": "2.0.4",
    "license": "MIT",
    "url": "https://github.com/inspect-js/hasOwn#readme",
    "standalone": false
  },
  {
    "name": "http-errors",
    "version": "2.0.1",
    "license": "MIT",
    "url": "jshttp/http-errors",
    "standalone": false
  },
  {
    "name": "iconv-lite",
    "version": "0.4.24",
    "license": "MIT",
    "url": "https://github.com/ashtuchkin/iconv-lite",
    "standalone": false
  },
  {
    "name": "inherits",
    "version": "2.0.4",
    "license": "ISC",
    "url": "https://github.com/isaacs/inherits",
    "standalone": false
  },
  {
    "name": "ipaddr.js",
    "version": "1.9.1",
    "license": "MIT",
    "url": "https://github.com/whitequark/ipaddr.js",
    "standalone": false
  },
  {
    "name": "math-intrinsics",
    "version": "1.1.0",
    "license": "MIT",
    "url": "https://github.com/es-shims/math-intrinsics#readme",
    "standalone": false
  },
  {
    "name": "media-typer",
    "version": "0.3.0",
    "license": "MIT",
    "url": "jshttp/media-typer",
    "standalone": false
  },
  {
    "name": "merge-descriptors",
    "version": "1.0.3",
    "license": "MIT",
    "url": "sindresorhus/merge-descriptors",
    "standalone": false
  },
  {
    "name": "methods",
    "version": "1.1.2",
    "license": "MIT",
    "url": "jshttp/methods",
    "standalone": false
  },
  {
    "name": "mime",
    "version": "1.6.0",
    "license": "MIT",
    "url": "https://github.com/broofa/node-mime",
    "standalone": false
  },
  {
    "name": "mime-db",
    "version": "1.52.0",
    "license": "MIT",
    "url": "jshttp/mime-db",
    "standalone": false
  },
  {
    "name": "mime-types",
    "version": "2.1.35",
    "license": "MIT",
    "url": "jshttp/mime-types",
    "standalone": false
  },
  {
    "name": "ms",
    "version": "2.0.0",
    "license": "MIT",
    "url": "zeit/ms",
    "standalone": false
  },
  {
    "name": "ms",
    "version": "2.1.3",
    "license": "MIT",
    "url": "zeit/ms",
    "standalone": false
  },
  {
    "name": "negotiator",
    "version": "0.6.3",
    "license": "MIT",
    "url": "jshttp/negotiator",
    "standalone": false
  },
  {
    "name": "object-inspect",
    "version": "1.13.4",
    "license": "MIT",
    "url": "https://github.com/inspect-js/object-inspect",
    "standalone": false
  },
  {
    "name": "on-finished",
    "version": "2.4.1",
    "license": "MIT",
    "url": "jshttp/on-finished",
    "standalone": false
  },
  {
    "name": "parseurl",
    "version": "1.3.3",
    "license": "MIT",
    "url": "pillarjs/parseurl",
    "standalone": false
  },
  {
    "name": "path-to-regexp",
    "version": "0.1.13",
    "license": "MIT",
    "url": "https://github.com/pillarjs/path-to-regexp",
    "standalone": false
  },
  {
    "name": "proxy-addr",
    "version": "2.0.8",
    "license": "MIT",
    "url": "jshttp/proxy-addr",
    "standalone": false
  },
  {
    "name": "qs",
    "version": "6.16.0",
    "license": "BSD-3-Clause",
    "url": "https://github.com/ljharb/qs",
    "standalone": false
  },
  {
    "name": "range-parser",
    "version": "1.2.1",
    "license": "MIT",
    "url": "jshttp/range-parser",
    "standalone": false
  },
  {
    "name": "raw-body",
    "version": "2.5.3",
    "license": "MIT",
    "url": "stream-utils/raw-body",
    "standalone": false
  },
  {
    "name": "safe-buffer",
    "version": "5.2.1",
    "license": "MIT",
    "url": "https://github.com/feross/safe-buffer",
    "standalone": false
  },
  {
    "name": "safer-buffer",
    "version": "2.1.2",
    "license": "MIT",
    "url": "https://github.com/ChALkeR/safer-buffer",
    "standalone": false
  },
  {
    "name": "send",
    "version": "0.19.2",
    "license": "MIT",
    "url": "pillarjs/send",
    "standalone": false
  },
  {
    "name": "serve-static",
    "version": "1.16.3",
    "license": "MIT",
    "url": "expressjs/serve-static",
    "standalone": false
  },
  {
    "name": "setprototypeof",
    "version": "1.2.0",
    "license": "ISC",
    "url": "https://github.com/wesleytodd/setprototypeof",
    "standalone": false
  },
  {
    "name": "side-channel",
    "version": "1.1.1",
    "license": "MIT",
    "url": "https://github.com/ljharb/side-channel#readme",
    "standalone": false
  },
  {
    "name": "side-channel-list",
    "version": "1.0.1",
    "license": "MIT",
    "url": "https://github.com/ljharb/side-channel-list#readme",
    "standalone": false
  },
  {
    "name": "side-channel-map",
    "version": "1.0.1",
    "license": "MIT",
    "url": "https://github.com/ljharb/side-channel-map#readme",
    "standalone": false
  },
  {
    "name": "side-channel-weakmap",
    "version": "1.0.2",
    "license": "MIT",
    "url": "https://github.com/ljharb/side-channel-weakmap#readme",
    "standalone": false
  },
  {
    "name": "statuses",
    "version": "2.0.2",
    "license": "MIT",
    "url": "jshttp/statuses",
    "standalone": false
  },
  {
    "name": "toidentifier",
    "version": "1.0.1",
    "license": "MIT",
    "url": "component/toidentifier",
    "standalone": false
  },
  {
    "name": "type-is",
    "version": "1.6.18",
    "license": "MIT",
    "url": "jshttp/type-is",
    "standalone": false
  },
  {
    "name": "unpipe",
    "version": "1.0.0",
    "license": "MIT",
    "url": "stream-utils/unpipe",
    "standalone": false
  },
  {
    "name": "utils-merge",
    "version": "1.0.1",
    "license": "MIT",
    "url": "https://github.com/jaredhanson/utils-merge",
    "standalone": false
  },
  {
    "name": "vary",
    "version": "1.1.2",
    "license": "MIT",
    "url": "jshttp/vary",
    "standalone": false
  }
];
