#!/usr/bin/env node
// Third-party notices: every production dependency shipped with Silinx ISE (the app zip includes
// node_modules; the single-file Silinx-ISE.html embeds CodeMirror and elkjs), with its licence text.
//   node scripts/third-party.mjs          writes THIRD-PARTY-NOTICES.md and core/third-party.js
//   node scripts/third-party.mjs --check  fails when they are out of date (used by the tests)
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
// embedded in the standalone Silinx-ISE.html (scripts/build-standalone.mjs)
const STANDALONE = new Set(['codemirror', 'elkjs']);
// where to get the source of copyleft components (EPL-2.0 asks for it)
const SOURCE = { elkjs: 'https://github.com/kieler/elkjs' };

function productionDeps() {
  const tree = JSON.parse(execFileSync('npm', ['ls', '--omit=dev', '--all', '--json'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], shell: process.platform === 'win32' }));
  const seen = new Map();
  const walk = (deps, dir) => {
    for (const [name, info] of Object.entries(deps || {})) {
      const key = `${name}@${info.version}`;
      if (!seen.has(key)) {
        // the package folder: npm puts most at the top level, conflicting versions nested
        const cands = [path.join(dir, 'node_modules', name), path.join(root, 'node_modules', name)];
        const pkgDir = cands.find(d => { try { return JSON.parse(fs.readFileSync(path.join(d, 'package.json'), 'utf8')).version === info.version; } catch { return false; } }) || cands[1];
        seen.set(key, { name, version: info.version, dir: pkgDir });
      }
      walk(info.dependencies, path.join(dir, 'node_modules', name));
    }
  };
  walk(tree.dependencies, root);
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version, undefined, { numeric: true }));
}

function describe(d) {
  const pkg = JSON.parse(fs.readFileSync(path.join(d.dir, 'package.json'), 'utf8'));
  const license = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type || (pkg.licenses || []).map(l => l.type || l).join(' OR ') || 'UNKNOWN';
  const repo = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url || '';
  const url = (pkg.homepage || repo).replace(/^git\+/, '').replace(/^git:\/\//, 'https://').replace(/\.git$/, '').replace(/^github:/, 'https://github.com/') || `https://www.npmjs.com/package/${d.name}`;
  const file = fs.readdirSync(d.dir).find(f => /^(licen[cs]e|copying)(\.(md|txt|markdown))?$/i.test(f)) || fs.readdirSync(d.dir).find(f => /^licen[cs]e/i.test(f));
  let text = file ? fs.readFileSync(path.join(d.dir, file), 'utf8').replace(/\r\n/g, '\n').trim() : '';
  // no licence file in the package: the text kept in scripts/licences/ (e.g. @yowasp/yosys: YoWASP,
  // Yosys and ABC, which its WebAssembly build contains)
  const kept = path.join(root, 'scripts', 'licences', `${d.name.replace('/', '__')}.txt`);
  if (!text && fs.existsSync(kept)) text = fs.readFileSync(kept, 'utf8').replace(/\r\n/g, '\n').trim();
  if (!text) {   // no licence file: the License section of the README (e.g. cookie-signature)
    const readme = fs.readdirSync(d.dir).find(f => /^readme(\.(md|markdown|txt))?$/i.test(f));
    const m = readme && /^#+\s*licen[cs]e\b.*\n([\s\S]*?)(?=\n#+\s|(?![\s\S]))/im.exec(fs.readFileSync(path.join(d.dir, readme), 'utf8').replace(/\r\n/g, '\n'));
    if (m) text = m[1].trim();
  }
  return { name: d.name, version: d.version, license, url, text, standalone: STANDALONE.has(d.name), source: SOURCE[d.name] || null };
}

export function build() {
  const comps = productionDeps().map(describe);
  const own = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  const md = [
    '# Third-party notices',
    '',
    `Silinx ISE (Copyright 2026 Pedro Maló, ${own.license}) includes the open-source components listed`,
    'below. The app (silinx-ise-<version>.zip) ships all of them; the single-file Silinx-ISE.html',
    'embeds the ones marked *standalone*. Each one keeps its own licence, reproduced in full here.',
    'This file is generated by `node scripts/third-party.mjs` from the installed dependencies.',
    '',
    '| Component | Version | Licence | In Silinx-ISE.html | Project |',
    '|---|---|---|---|---|',
    ...comps.map(c => `| ${c.name} | ${c.version} | ${c.license} | ${c.standalone ? 'standalone' : ''} | ${c.url} |`),
    '',
    ...comps.filter(c => c.source).map(c => `The source code of ${c.name} (${c.license}) is available at ${c.source}.`),
    '',
    ...comps.flatMap(c => [`## ${c.name} ${c.version} — ${c.license}`, '', c.url, '', '```text', c.text || `(no licence file in the package; licence: ${c.license})`, '```', '']),
  ].join('\n');
  const js = [
    '// Silinx - open-source components shipped with Silinx ISE (shown in Help ▸ About).',
    '// Generated by scripts/third-party.mjs from the production dependencies: do not edit.',
    `export const THIRD_PARTY = ${JSON.stringify(comps.map(({ name, version, license, url, standalone }) => ({ name, version, license, url, standalone })), null, 2)};`,
    '',
  ].join('\n');
  return { md, js, comps };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const { md, js, comps } = build();
  const files = [[path.join(root, 'THIRD-PARTY-NOTICES.md'), md], [path.join(root, 'core/third-party.js'), js]];
  if (process.argv.includes('--check')) {
    const stale = files.filter(([f, t]) => { try { return fs.readFileSync(f, 'utf8') !== t; } catch { return true; } }).map(([f]) => path.relative(root, f));
    if (stale.length) { console.error(`out of date: ${stale.join(', ')} — run: node scripts/third-party.mjs`); process.exit(1); }
    console.log(`third-party notices up to date (${comps.length} components)`);
  } else {
    for (const [f, t] of files) fs.writeFileSync(f, t);
    console.log(`wrote THIRD-PARTY-NOTICES.md and core/third-party.js (${comps.length} components)`);
  }
}
